on: push

name: npm build, lint, test and publish

jobs:
  build-and-publish:
    defaults:
      run:
        working-directory: sample-app

    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: npm install
        run: npm install

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./sample-app
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simple-nodejs-k8s-master-develop:latest

  upload_to_azure_registry:
    defaults:
      run:
        working-directory: sample-app

    name: upload to azure repository
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Azure repository login
        uses: azure/docker-login@v1
        with:
          login-server: "simplenodejsk8smaster.azurecr.io"
          username: ${{ secrets.AZURE_CONTAINER_ACCESS_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_ACCESS_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./sample-app
          push: true
          tags: ${{ secrets.AZURE_CONTAINER_ACCESS_USERNAME }}/simple-nodejs-k8s-master-develop:latest
